# /// script
# requires-python = ">=3.9"
# dependencies = ["jinja2>=3.1,<4", "openpyxl>=3.1,<4"]
# ///
"""Generate one framework's metadata without changing its editorial fiche.

Run: uv run gen.py --help
The historical bulk generator is archived in scripts/legacy_gen.py.
"""

import argparse
import csv
from datetime import date
import io
import json
from pathlib import Path
import re
import sys
from urllib.parse import parse_qs, quote, urlencode, urlsplit
from urllib.request import urlopen

from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = Path(__file__).resolve().parent
MARKER = "% Generated by gen.py; edit the catalogue snapshot, not this file.\n"
LATEX = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def clean(value):
    return "" if value is None else str(value).strip()


def latex(value):
    """Escape source text once, including backslashes and multiline cells."""
    return "".join(LATEX.get(c, c) for c in " ".join(clean(value).split()))


def link(value, label):
    value = clean(value)
    parsed = urlsplit(value)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Expected an HTTP(S) URL: " + value)
    value = quote(value, safe=":/?&=+#%@-._~")
    return r"\href{" + latex(value) + "}{" + latex(label) + "}"


def benchmark_flag(value):
    """Google exports use strings; bool('FALSE') must not mean benchmarked."""
    if value is None or clean(value) == "":
        return None
    token = clean(value).casefold()
    if token in {"true", "yes", "1", "1.0"}:
        return True
    if token in {"false", "no", "0", "0.0"}:
        return False
    raise ValueError("Invalid WP benchmark flag: " + repr(value))


def select_row(rows, framework, source):
    rows = iter(rows)
    headers = [clean(h) for h in next(rows, [])]
    name_key = "Name" if "Name" in headers else "Software"
    if name_key not in headers:
        raise ValueError("Expected a Name (Frameworks) or Software column")
    nonempty = [h for h in headers if h]
    if len(nonempty) != len(set(nonempty)):
        raise ValueError("Duplicate column names in catalogue")
    matches = []
    for number, values in enumerate(rows, 2):
        entry = dict(zip(headers, values))
        if clean(entry.get(name_key)).casefold() == framework.strip().casefold():
            entry = {key: value for key, value in entry.items() if key}
            entry["Name"] = clean(entry[name_key])
            if name_key == "Software":
                del entry["Software"]
            matches.append({"source": dict(source, row=number), "framework": entry})
    if len(matches) != 1:
        raise ValueError(
            f"Expected one exact match for {framework!r}; found {len(matches)}"
        )
    return matches[0]


def load_local(path, framework, sheet=None):
    source = {"file": path.name, "retrieved_at": date.today().isoformat()}
    if path.suffix.lower() == ".json":
        data = json.loads(path.read_text(encoding="utf-8"))
        if clean(data["framework"]["Name"]).casefold() != framework.strip().casefold():
            raise ValueError("Snapshot does not match the requested framework")
        return data
    if path.suffix.lower() == ".csv":
        with path.open(encoding="utf-8-sig", newline="") as stream:
            return select_row(
                csv.reader(stream), framework, dict(source, sheet=sheet or "Catalogue")
            )
    if path.suffix.lower() != ".xlsx":
        raise ValueError("Input must be .xlsx, .csv, or a catalogue .json snapshot")
    from openpyxl import load_workbook

    workbook = load_workbook(path, read_only=True, data_only=True)
    try:
        if sheet is None:
            sheet = next(
                (s for s in ("Frameworks", "Software") if s in workbook.sheetnames),
                None,
            )
        if sheet not in workbook.sheetnames:
            raise ValueError("No Frameworks/Software worksheet; specify --sheet")
        return select_row(
            workbook[sheet].iter_rows(values_only=True),
            framework,
            dict(source, sheet=sheet),
        )
    finally:
        workbook.close()


def load_google(url, framework, sheet=None):
    """Read-only CSV export; private sheets can be exported and passed as input.

    No credentials or cookies are requested or stored.
    """
    parsed = urlsplit(url)
    match = re.fullmatch(r"/spreadsheets/d/([A-Za-z0-9_-]+)(?:/.*)?", parsed.path)
    if parsed.scheme != "https" or parsed.netloc != "docs.google.com" or not match:
        raise ValueError("--sheet-url must be a docs.google.com spreadsheet URL")
    query = parse_qs(parsed.query)
    fragment = parse_qs(parsed.fragment)
    gid = fragment.get("gid", query.get("gid", ["0"]))[0]
    if not gid.isdigit():
        raise ValueError("Sheet gid must be an integer")
    export = f"https://docs.google.com/spreadsheets/d/{match[1]}/export?"
    export += urlencode({"format": "csv", "gid": gid})
    with urlopen(export, timeout=30) as response:
        payload = response.read(5_000_001)
        if "html" in response.headers.get("Content-Type", "").lower():
            raise ValueError("Sheet requires authentication; export it and use --input")
    if len(payload) > 5_000_000:
        raise ValueError("CSV export exceeds 5 MB")
    source = {"url": url, "gid": gid, "retrieved_at": date.today().isoformat()}
    if sheet:
        source["sheet"] = sheet
    return select_row(
        csv.reader(io.StringIO(payload.decode("utf-8-sig"))), framework, source
    )


def render(data):
    entry, source = data["framework"], data["source"]
    fields = [
        ("Name", "Framework"),
        ("Partner", "Exa-MA partner"),
        ("Emails", "Contacts"),
        ("Consortium", "Consortium"),
        ("License", "Licence category (survey)"),
        ("Benchmarked", "Architecture category (survey)"),
        ("Bottlenecks", "Bottlenecks"),
        ("Languages", "Languages"),
        ("Parallelism", "Parallel programming"),
        ("Data", "Data formats"),
        ("DevOps", "Development practices"),
        ("Resilience", "Resilience"),
        ("Training", "Training resources"),
        ("API", "API policy"),
        ("Metadata", "Metadata / versioning"),
        ("Interfaces", "Interfaces"),
    ]
    rows = [
        (latex(label), latex(entry[key]))
        for key, label in fields
        if clean(entry.get(key))
    ]
    for key, label in [
        ("Repository", "Source repository"),
        ("Docs", "Documentation"),
        ("Training URL", "Training material"),
        ("Channels", "Support"),
    ]:
        if clean(entry.get(key)):
            rows.append((label, link(entry[key], label)))
    work_packages = [
        (f"WP{i}", latex(entry[f"WP{i}"]))
        for i in range(1, 8)
        if clean(entry.get(f"WP{i}"))
    ]
    flags = [
        (f"WP{i}", benchmark_flag(entry.get(f"WP{i} Benchmarked"))) for i in range(1, 8)
    ]
    checked = [wp for wp, flag in flags if flag is True]
    missing = [wp for wp, flag in flags if flag is None]
    status = (
        "Benchmark flags checked in the survey: " + ", ".join(checked) + "."
        if checked
        else "No WP benchmark flag is checked in this snapshot."
    )
    if missing:
        status += " Flags not supplied: " + ", ".join(missing) + "."
    source_name = source.get("sheet", "Catalogue")
    if source.get("row"):
        source_name += ", row " + str(source["row"])
    source_label = (
        link(source["url"], source_name) if source.get("url") else latex(source_name)
    )
    environment = Environment(
        loader=FileSystemLoader(ROOT / "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        block_start_string=r"\BLOCK{",
        block_end_string="}",
        variable_start_string=r"\VAR{",
        variable_end_string="}",
        comment_start_string=r"\#{",
        comment_end_string="}",
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return MARKER + environment.get_template("framework-metadata.tex.j2").render(
        rows=rows,
        work_packages=work_packages,
        status=latex(status),
        source=source_label,
        retrieved_at=latex(source["retrieved_at"]),
    )


def validate_output(path):
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER):
        raise ValueError(f"Refusing to overwrite non-generated file: {path}")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    inputs = parser.add_mutually_exclusive_group(required=True)
    inputs.add_argument(
        "--input", type=Path, help="Local XLSX, CSV, or selected-row JSON snapshot"
    )
    inputs.add_argument(
        "--sheet-url", help="Google Sheets URL (unauthenticated CSV export)"
    )
    parser.add_argument(
        "--framework", required=True, help="Exact name, case-insensitive"
    )
    parser.add_argument("--sheet", help="XLSX defaults to Frameworks, then Software")
    parser.add_argument(
        "--output", type=Path, help="Metadata file; otherwise print to stdout"
    )
    parser.add_argument(
        "--snapshot",
        type=Path,
        help="Save selected row and provenance to a NEW JSON file",
    )
    parser.add_argument(
        "--check", action="store_true", help="Check --output without writing"
    )
    args = parser.parse_args(argv)
    if args.check and (not args.output or args.snapshot):
        parser.error("--check requires --output and cannot be combined with --snapshot")
    paths = [p.resolve() for p in (args.input, args.output, args.snapshot) if p]
    if len(paths) != len(set(paths)):
        parser.error("Input, output, and snapshot paths must be distinct")
    try:
        data = (
            load_local(args.input, args.framework, args.sheet)
            if args.input
            else load_google(args.sheet_url, args.framework, args.sheet)
        )
        text = render(data)
        if args.check:
            if (
                not args.output.exists()
                or args.output.read_text(encoding="utf-8") != text
            ):
                raise ValueError(
                    "Generated metadata is out of date: " + str(args.output)
                )
            return 0
        # Validate both destinations before any write.
        if args.snapshot and args.snapshot.exists():
            raise ValueError(
                "Snapshot already exists; use a new path and review the diff"
            )
        if args.output:
            validate_output(args.output)
        if args.snapshot:
            args.snapshot.parent.mkdir(parents=True, exist_ok=True)
            with args.snapshot.open("x", encoding="utf-8") as stream:
                json.dump(data, stream, ensure_ascii=False, indent=2)
                stream.write("\n")
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(text, encoding="utf-8")
        else:
            sys.stdout.write(text)
    except (OSError, ValueError, KeyError, TypeError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    sys.exit(main())
